
STAGING ?= ../staging

LXCPATH ?= `sudo lxc-config lxc.lxcpath`
LXCNAME ?= "chromecast-widevine-tools-tests"

all: $(STAGING)

$(STAGING):
	echo "Please run 'sudo tests/lxc-bootstrap' to setup lxc for tests."
